# Generated by Django 4.2.4 on 2023-08-13 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteAdmin',
            fields=[
                (
                    'note_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='note.note',
                    ),
                ),
            ],
            bases=('note.note',),
        ),
    ]
