# Generated by Django 4.2.4 on 2023-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_noteadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(name='NoteAdmin',),
    ]
