# Generated by Django 4.2.4 on 2023-08-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_image_alter_note_text_delete_noteadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
